name: Deploy Angular 21 to GH Pages
on:
  push:
    branches: [main]
permissions:
  contents: write # Required to push to the gh-pages branch
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ› ï¸
        uses: actions/checkout@v4

      - name: Setup Node ğŸŸ¢
        uses: actions/setup-node@v4
        with:
          node-version: 22 # Angular 21 supports Node 20, 22, and 24

      - name: Install & Build ğŸ—ï¸
        run: |
          npm ci
          # REPLACE 'ng-similar-face' with your repo name
          npm run build -- --base-href /ng-similar-face/

      - name: Fix 404 Routing ğŸ› ï¸
        # This copies index.html to 404.html so refreshing routes works
        run: cp dist/ng-similar-face/browser/index.html dist/ng-similar-face/browser/404.html

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/ng-similar-face/browser
          branch: gh-pages
